[pytest]
asyncio_mode = auto
pythonpath =
    identity_notification_consumer/src
    identity_store_consumer/src
    ../notification/src
    ../identity/src
    ../store/src
testpaths =
    identity_notification_consumer/tests
    identity_store_consumer/tests
