[pytest]
asyncio_mode = auto
addopts = --no-cov
pythonpath =
    identity_notification_consumer/src
    identity_store_consumer/src
    multi_auth_host_consumer/src
    ../notification/src
    ../identity/src
    ../integration_auth/src
    ../store/src
testpaths =
    identity_notification_consumer/tests
    identity_store_consumer/tests
    multi_auth_host_consumer/tests
